### ISSUE TITLE
Use Branch-State for Base Image in GitHub Build-Workflow

### ISSUE THREAD

**Issue by schote** [brain-link/scanhub#99]
ScanHub services are build on the ScanHub base image. The base image is either taken from GitHub container registry (ghcr) or from a manual build using the repository code. The source of the base image is configured in the `.env` file by setting the environment variable `SCANHUB_BASE_IMAGE`.

### Problem Description

If changes are made to the base-image (and the ScanHub services) the modified base image is required to build the service(s). However, within the GitHub build action, the ghcr image is taken per default. The base image is deployed to the ghcr only on pushes to main, which require a PR with a succeeding build (requires up to date base image).

### Solution

The GitHub build workflow should depend on a manual build of the base image and not on the image from ghcr. 

Options/ideas:

- Change default in `.env`
- Use different environment for GitHub build workflow
- Overwrite `.env` file in GitHub action

**Comment by chdinh** [comment]
Since we are using the standard environment setup of docker compose we can inject the mnaul build of the base image via a command line argument as described here:
https://docs.docker.com/compose/environment-variables/set-environment-variables/
![image](https://github.com/brain-link/scanhub/assets/912787/57a7a488-b30b-4819-a780-30d92b0f0238)

This will overwrite the .env variable

**Comment by schote** [comment]
Thank you @chdinh, so within the github workflow we will build the base-image and run the docker-compose with the modified variable
